### ISSUE TITLE
Events aren't triggered

### ISSUE THREAD

**Issue by Chorok322** [Webbeh/WorldGuard-Events#9]
Server verison : 1.18.1 with paper

Worldguard version : 7.0.6
WorldguardEvents version : 1.18.1

First of all, I am sorry for my poor English.
English is not my first language.

While coding the plugin using this API, I realized that the event was not triggered.

At first, I thought it was a problem with my coding skills
But it doesn't work even though it's very simple to code.

```java
public final class Main extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
        this.logger.info("Plugin On");
    }
    
    @Override
    public void onDisable() {
        this.logger.info("Plugin off");
    }

    @EventHandler
    public void onAFK(RegionEnteredEvent e) {
        e.getPlayer().sendMessage("ON");
    }
    
    @EventHandler
    public void offAFK(RegionLeftEvent e) {
        e.getPlayer().sendMessage("OFF");
    }
}
```

**Comment by Webbeh** [comment]
Hey, @Chorok322 

The plugin works properly for most people, and so on all versions since 1.13.

There's multiple reasons why it might not work, but the most likely contenders are : 
- You didn't put the WorldGuardEvents jar inside the "plugins" folder
- You didn't create any worldguard regions
- You did create worldguard regions but are not trying to walk in&out of them
- ...Your chat is off ?

One good thing you could do is send me the logs of your minecraft server after startup.

Also, I don't know what you're trying to do with the `onAFK` and `offAFK` methods. It will "work" (by sending an "ON" message whenever a player enters ANY region, and sending an OFF message whenevera  player leaves ANY region), but I don't think it's what you intended it to do...

**Comment by Webbeh** [comment]
Closing this as it's most likely a comprehension problem and not a code problem. You're welcome to send me details and I will re-open if needed.
